name: Review Requested Workflow

on:
  pull_request:
    types:
      - review_requested

jobs:
  show-requested-reviewers:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Get requested reviewers
      - name: Display requested reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching the list of requested reviewers..."
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
               | jq '.requested_reviewers | map(.login) | join(", ")' \
               || echo "No reviewers requested"
