name: Set Required Approvals to 2

on:
  workflow_dispatch: # Manually trigger this workflow if needed
  pull_request:
    types:
      - review_requested

jobs:
  update-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Set Required Approvals to 2
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Replace 'YOUR_BRANCH_RULE_ID' with your branch protection rule ID
          branch_protection_rule_id=2788173

          # Update the branch protection rule to set required approvals to 2
          curl -s -X POST \
            -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"query\": \"mutation { updateBranchProtectionRule(input: { branchProtectionRuleId: \\\"$branch_protection_rule_id\\\", requiredApprovingReviewCount: 2 }) { branchProtectionRule { id requiredApprovingReviewCount } } }\"
            }" \
            https://api.github.com/graphql
